# This file defines the environment variables that this chart supports to be loaded under .Values.container

optional:
  - SCRP_API_URL
  - SCRP_EXPERIAN_API_URL
  - SCRP_PAYMENT_GATEWAY_API_URL
required:
  - SCRP_API_KEY
  - SCRP_EXPERIAN_API_KEY
    
# secrets:
#   required:
    
#   optional: